[project]
name = "mintnft"
authors = []
description = ""
telemetry = false

[[project.requirements]]
contract_id = "ST3QFME3CANQFQNR86TYVKQYCFT7QX4PRXM1V9W6H.sip009-nft-trait.sip009-nft-trait"

[contracts.mint-nft]
path = "contracts/mint-nft.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = true
trusted_caller = false
callee_filter = false
